<?php
/**
 * @var $statusCode string
 * @var $message string
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Error <?= $statusCode; ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="/assets/css/normalize.css">
    <link rel="stylesheet" href="/assets/css/skeleton.css">
    <link id="favicon" rel="icon" type="image/png" href="/favicon.png" />
</head>
<body>
<div class="container">
    <div class="row">
        <div class="one-half column" style="margin-top: 25%">
            <h1>Oops!</h1>
            <h3>The server returned a <strong style="font-size: larger"><?= $statusCode; ?></strong></h3>
            <p><?= $message; ?>"</p>.
        </div>
    </div>
</div>
</body>
</html>

