<?php
/**
 * @var $title string
 * @var $user App\Entity\User
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>RedCrown Test Task - <?= $title; ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="/assets/css/normalize.css">
    <link rel="stylesheet" href="/assets/css/skeleton.css">
    <link id="favicon" rel="icon" type="image/png" href="/favicon.png" />
    <style type="text/css">
        .two-half.column {
            margin-top: 25%
        }
        h1.name span {
            font-size: 60%;
        }
    </style>
</head>
<body>
<div class="container">
    <div class="row">

        <div class="two-half column">
            <h1 class="name"><span>#<?= $user->getId(); ?></span> <?= $user->name; ?></h1>
            <h4><?= $user->getStatusName(); ?></h4>
        </div>
    </div>
</div>
</body>
</html>